# Generated by Django 3.0.3 on 2020-03-13 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitut_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrient_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
    ]
