# Generated by Django 3.0.3 on 2020-03-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('substitut_search', '0003_favory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favory',
            name='user',
        ),
        migrations.AddField(
            model_name='favory',
            name='user_profil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Profil'),
            preserve_default=False,
        ),
    ]
