# Generated by Django 3.0.3 on 2020-03-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitut_search', '0004_auto_20200314_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favory',
            old_name='user_profil',
            new_name='user_profile',
        ),
    ]
